name: Build Electron App

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./backend
        run: npm install

      - name: Build Windows App
        working-directory: ./backend
        run: npm run build:exe
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-setup
          path: backend/dist-electron/*.exe

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./backend
        run: npm install

      - name: Build Mac App
        working-directory: ./backend
        run: npm run build:mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Upload Mac Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-setup
          path: backend/dist-electron/*.dmg
