name: Build Electron App

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./backend
        run: npm install

      - name: Create .env file
        working-directory: ./backend
        shell: bash
        run: |
          echo "PORT=3000" > .env
          echo "MONGODB_URI=mongodb+srv://gunesgozlemcisi_db_user:adana123@cluster0.azseniu.mongodb.net/inonu_site?retryWrites=true&w=majority&appName=Cluster0" >> .env

      - name: Build Windows App
        working-directory: ./backend
        run: npm run build:exe
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-setup
          path: dist-electron/*.exe

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./backend
        run: npm install

      - name: Create .env file
        working-directory: ./backend
        run: |
          echo "PORT=3000" > .env
          echo "MONGODB_URI=mongodb+srv://gunesgozlemcisi_db_user:adana123@cluster0.azseniu.mongodb.net/inonu_site?retryWrites=true&w=majority&appName=Cluster0" >> .env

      - name: Build Mac App
        working-directory: ./backend
        run: npm run build:mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Upload Mac Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-setup
          path: dist-electron/*.dmg
